---
name: default-bare

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:  # run weekly, every Monday 01:00
    - cron: '0 1 * * 1'
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions: {}

jobs:
  build:

    permissions:
      contents: read
    runs-on: ${{ matrix.distribution }}-${{ matrix.version }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        include:
          - distribution: ubuntu
            version: '24.04'
            suite: default
            experimental: false
    env:
      PYINFRA_DIR: pyinfra-harden-nanokvm

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76  # v2.14.0
        with:
          egress-policy: block
          allowed-endpoints: >
            azure.archive.ubuntu.com:80
            esm.ubuntu.com:443
            files.pythonhosted.org:443
            galaxy.ansible.com:443
            github.com:443
            packages.microsoft.com:443
            pypi.org:443
            www.google.com:1025
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1
        with:
          path: ${{ env.PYINFRA_DIR }}
      - name: Set up Python
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548  # v6.1.0
        with:
          python-version: '3.x'
      - name: Cache
        uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb  # v5.0.1
        with:
          path: |
            /var/cache/apt/archives
            /var/lib/apt
            /var/_install
          key: cache-${{ env.PYINFRA_DIR }}-${{ steps.get-date.outputs.date }}
      - name: Install dependencies
        run: |
          cd $GITHUB_WORKSPACE/$PYINFRA_DIR
          [ -f requirements.txt ] && pip install -r requirements.txt
          [ -f requirements-dev.txt ] && pip install -r requirements-dev.txt
          pip3 show pyinfra
      - name: Environment
        run: |
          set -x
          pwd
          env
          find . -ls
      - name: Set testing conditions
        run: |
          sudo touch /boot/resolv.conf
          ls -lA /boot
      - name: Run test
        run: |
          cd $GITHUB_WORKSPACE/$PYINFRA_DIR && pyinfra @local nanokvm_deploy.py -y
        env:
          PY_COLORS: '1'
      - name: Idempotency run
        run: |
          cd $GITHUB_WORKSPACE/$PYINFRA_DIR && pyinfra @local nanokvm_deploy.py -y | tee /tmp/idempotency.log
          cat /tmp/idempotency.log | grep -qE 'Success|Error'  && (echo 'Idempotence test: fail' && exit 1)  || (echo 'Idempotence test: pass' && cat /tmp/idempotency.log && exit 0)
        env:
          PY_COLORS: '1'
      - name: Verify
        run: |
          cd $GITHUB_WORKSPACE/$PYINFRA_DIR && pytest tests/test_*.py
        env:
          PY_COLORS: '1'
      - name: On failure
        run: |
          systemctl -l --no-pager status
          systemctl -l --no-pager --failed
          ls -l /usr/bin/ | egrep '(python|pip|pyinfra)'
          pip freeze
          pip3 freeze
          ip addr
          cat /etc/resolv.conf
          host www.google.com
          ping -c 1 www.google.com || true
          ping -c 1 8.8.8.8 || true
        if: ${{ failure() }}
        continue-on-error: true
      - name: After script - etc/boot
        run: |
          set -x
          cat /etc/environment
          cat /boot/resolv.conf || true
          cat /etc/resolv.conf || true
          sudo cat /etc/ssh/sshd_config || true
          grep -qs -- 'OpenBSD: sshd_config,' /etc/ssh/sshd_config || true
          sudo grep -qs -- 'OpenBSD: sshd_config,' /etc/ssh/sshd_config || true
          cat /etc/iptables.conf || true
          cat /etc/ip6tables.conf || true
          cat /etc/udhcpc/udhcpc.conf || true
        if: ${{ always() }}
        continue-on-error: true
      - name: After script - logs
        run: |
          sudo tail -n500 /var/log/messages
        if: ${{ always() }}
        continue-on-error: true
      - name: After script - pyinfra-debug.log
        run: |
          tail -n500 pyinfra-debug.log
        if: ${{ always() }}
        continue-on-error: true
